In [1]:
import visualProjector as vp
import matplotlib.pyplot as plt
import numpy as np
from imp import reload
import random


reload(vp)

<module 'visualProjector' from 'C:\\Users\\renaud\\Documents\\3DVisualSwarm\\src\\visualProjector.py'>

In [2]:
scene = vp.Scene()
for k in range(0,10):
    scene.addObject((10*random.random(),10*random.random(),10*random.random()),(0,0,2*np.pi*random.random()))

In [3]:
scene.computeVisualField(3)

[[11.08966394 -2.45196277 -0.41216226]
 [11.16814419 -2.41333804 -0.45424773]
 [ 8.33990937 -2.04428687 -0.54197206]
 [ 5.25421653  2.33098862  0.75061151]
 [ 4.33496817 -2.06633016  0.4712806 ]
 [ 8.26209082 -1.7556274  -0.59154203]
 [ 8.09016768  2.9768316  -0.29460406]
 [ 5.32535511 -1.69829063  0.02286996]
 [ 1.35584008  1.61959659 -0.81420327]]
[11.08966394 -2.45196277 -0.41216226]


C:\Users\renaud\Documents\3DVisualSwarm\src\visualProjector.py:156: RuntimeWarning: invalid value encountered in sqrt
  phiLim = np.sqrt((thetaApp**2 - thetaSpace**2) / (np.cos(theta)**2))


UnboundLocalError: local variable 'vIdx' referenced before assignment

[[ 4.64056951  2.55819523 -0.01933335]
 [ 2.93886953  0.31370491 -0.03862705]
 [ 6.76545822 -1.48880692  0.89581949]
 [ 7.64621903 -1.6110779   0.76975118]
 [ 7.82399667 -2.14452796  0.25799236]
 [ 4.65828167  2.36774777 -0.30047381]
 [ 7.09911805 -1.84862515  0.78361275]
 [ 8.06760459 -1.2022533   0.99873885]
 [ 6.07786976 -0.21493544  1.1636584 ]]


NameError: name 'drawSphere' is not defined

In [64]:
k=3
np.delete(scene.position - scene.position[k,:],k,0)

array([[-3.87227675,  2.55583838, -0.08971217],
       [ 2.79335814,  0.90621411, -0.11349164],
       [ 0.34622976, -4.2133928 ,  5.28193819],
       [-0.22111126, -5.48617252,  5.32143648],
       [-4.10608444, -6.35374898,  1.99621352],
       [-3.18246332,  3.1097642 , -1.37872477],
       [-1.37923779, -4.835951  ,  5.01086401],
       [ 1.57342225, -4.07423964,  6.78315248],
       [ 2.35135358, -0.5133183 ,  5.58105201]])

In [22]:
try:
    bodySize
except:
    print('nop')

nop
